export const strings: { [textString: string]: string } = {
	button_next: 'Next',
	button_mainPage: 'Main Page',
	button_practice: 'Start Practice',
	button_stats: 'View Stats',
	button_signIn: 'Sign In',
	button_signOut: 'Sign Out',
	button_register: 'Create Account',
	button_cancel: 'Cancel',
	button_back: 'Back',
	button_clearData: 'Clear Data',
	counter_correct: 'Correct',
	counter_incorrect: 'Incorrect',
	dialog_signOut: 'Are you sure you want to sign out?',
	dialog_clearStats:
		'Are you sure you want to clear your practice statistics? This action cannot be undone.',
	error_register:
		'We were unable to create your account due to the following error',
	error_signIn: 'We were unable to log you in due to the following error',
	practice_hiragana: 'Hiragana',
	practice_katakana: 'Katakana',
	practice_both: 'Both',
	practice_character: 'Choose Character',
	practice_reading: 'Choose Reading',
	practice_selectKana: 'Which set of characters would you like to practice?',
	practice_selectMode: 'How would you like to practice?',
	question_character:
		'Choose the character that corresponds to the reading below',
	question_reading:
		'Choose the reading that corresponds to the character below',
	register_title: 'Create an account',
	register_usernameHelper: 'Minimum Length: 3 characters',
	register_passwordHelper: 'Minimum Length: 6 characters',
	register_emailHelper:
		'An email is required in the event you forget your password',
	signIn_title: 'Sign in to your account',
	stats_timesSeen: 'Times seen',
	stats_correctAnswers: 'Correct answers',
	stats_accuracy: 'Accuracy',
	stats_na: 'N/A',
	stats_detailedStats: 'Detailed Stats',
	stats_characterStats: 'Choose Character stats',
	stats_readingStats: 'Choose Reading stats',
	stats_hiraganaStats: 'Hiragana Stats',
	stats_katakanaStats: 'Katakana Stats',
	stats_noStats:
		'There are no stats to display. Start practicing to get some data!',
	stats_register: 'Save your progress across browsers by creating an account!',
	stats_subheading:
		'For more information, you can click on a character for a detailed breakdown of your practice',
	stats_title: 'Your Practice Stats',
	username: 'Username',
	password: 'Password',
	email: 'Email',
};
